version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=flask_cv

volumes:
  postgres_data: