"""init db

Revision ID: 04cb38b59af8
Revises: 1bbd41ca5b5e
Create Date: 2022-09-25 10:51:22.231756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cb38b59af8'
down_revision = '1bbd41ca5b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('personal_information', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_information', 'address')
    op.drop_column('personal_information', 'phone')
    # ### end Alembic commands ###
