"""init db

Revision ID: 1bbd41ca5b5e
Revises: 49f392e0906a
Create Date: 2022-09-12 22:18:53.577735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbd41ca5b5e'
down_revision = '49f392e0906a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('birth_of_day', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('userpublic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userpublic_id'], ['user_public.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_information')
    # ### end Alembic commands ###
