"""init db

Revision ID: 49f392e0906a
Revises: 7ec60e024a99
Create Date: 2022-09-10 15:10:57.118705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f392e0906a'
down_revision = '7ec60e024a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_public_password_key', 'user_public', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_public_password_key', 'user_public', ['password'])
    # ### end Alembic commands ###
