"""init db

Revision ID: 8f7c2359f670
Revises: 28d86368695d
Create Date: 2022-11-02 23:47:33.528030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7c2359f670'
down_revision = '28d86368695d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('personal_information', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('personal_information', sa.Column('about', sa.String(length=255), nullable=True))
    op.add_column('personal_information', sa.Column('skills', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_information', 'skills')
    op.drop_column('personal_information', 'about')
    op.drop_column('personal_information', 'position')
    op.drop_column('personal_information', 'avatar_url')
    # ### end Alembic commands ###
