"""init db

Revision ID: ccaf80267b43
Revises: f06f8807ab37
Create Date: 2022-10-23 10:12:22.831567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf80267b43'
down_revision = 'f06f8807ab37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title_1', sa.String(length=255), nullable=True),
    sa.Column('title_2', sa.String(length=255), nullable=True),
    sa.Column('date_in', sa.String(length=255), nullable=True),
    sa.Column('date_out', sa.String(length=255), nullable=True),
    sa.Column('description_details', sa.String(length=1000), nullable=True),
    sa.Column('personalinformation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personalinformation_id'], ['personal_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    # ### end Alembic commands ###
